services:
  agent_pnmedia:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - "com.pnmediaplus.project=agent.pnmediaplus.com"
    container_name: agent_pnmedia
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    labels:
      - "com.pnmediaplus.project=agent.pnmediaplus.com"

  queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent_pnmedia_worker
    restart: unless-stopped
    command: ["node", "worker.js"]
    env_file:
      - .env
    labels:
      - "com.pnmediaplus.project=agent.pnmediaplus.com"
