version: '3.8'

services:
  agent_pnmedia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent_pnmedia
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
