import os

plan = """# Automated Marketing-to-CSKH Knowledge Handoff

## Goal
Implement a direct, automated handoff pipeline from the Marketing Agent Workspace to the CSKH (Omnichannel) Knowledge Base. When a marketing campaign is approved, the system should automatically convert the campaign context (Markdown/JSON) into a persistent document and ingest it into the `crm_knowledge_documents` table under the `cskh` namespace, triggering N8N for vectorization.

## User Review Required
> [!IMPORTANT]
> **State Machine & Transaction Integration:** To avoid conflicts with the existing `/api/phase2/approve-publish` route, we will separate the "Publish to Telegram/Social" and the "Sync to CSKH Knowledge Base" into a two-step process in the UI, or handle them via an Event-Driven background queue. 
> For Phase 1, we propose adding a distinct state: `QA_passed` -> `Publishing` -> `Published` -> `CSKH_Handoff_Pending` -> `CSKH_Handoff_Completed`. 

## Proposed Changes

### Backend: Internal Handoff API
#### [NEW] src/app/api/internal/handoff/marketing-to-cskh/route.ts
- Create a `POST` endpoint guarded by `verifyUiAuth`.
- **Payload Validation (Zod):** Validate `campaignId` (UUID), `title` (length limit), and `payload` (JSON size limit) to prevent abuse.
- **Tenant Ownership:** Force fetch the Campaign/Content from the database using the session's `organization_id` to verify ownership and ensure the item is generated by the Marketing department and is in a valid state (e.g., `Published` or `QA_passed`).
- **Idempotency:** Implement an `idempotency_key` based on `(organization_id, campaign_id, handoff_version)` to prevent duplicate entries if the webhook fires twice.
- **Processing & Rollback Strategy:**
  1. **Upload Storage:** Combine Markdown and JSON, upload to Supabase Storage.
  2. **DB Insert:** Insert a record into `crm_knowledge_documents`. Force `namespace = 'cskh'`. Add metadata: `campaign_id`, `source_department: 'marketing'`, `approved_by: userId`.
  3. **N8N Webhook Trigger:** Call the ingestion webhook with an authentication signature and a tight timeout.
  4. **Rollback:** If N8N fails, update the DB record to `status = 'failed'` (so it can be retried later by a cron or manually), preserving the audit log instead of blindly deleting the storage object.

### Frontend: Marketing Workspace Action Bar
#### [MODIFY] src/components/agents/marketing/ApprovalActionBar.tsx
- Wire up the UI to accept real props: `campaignId`, `contentState`.
- Separate the "Publish" action and "Sync to CSKH" action, or combine them into a sequential spinner state (Publishing... -> Syncing to CSKH... -> Done).
- Provide clear error toasts if the webhook fails, allowing the user to "Retry Sync" without republishing the campaign.

## Verification Plan

### Automated/Code Level
- **Zod Schema:** Verify all inputs are strictly typed and size-capped.
- **RLS/DB Check:** Ensure `requireCrmRouteContext` enforces `organization_id` filters on the campaign verification step.

### Manual Verification
1. Open the Marketing Agent workspace (`/agents/marketing`).
2. Click "Approve & Publish & Sync".
3. Check the Network tab to ensure idempotency keys are sent.
4. Verify the CSKH Knowledge Base (`/omnichannel/knowledge`) displays the new Campaign document with the correct metadata attached.
"""

with open("C:/Users/truon/.gemini/antigravity/brain/04ba1e97-e4ba-4383-9a48-5b4683a2a2a6/implementation_plan.md", "w", encoding="utf-8") as f:
    f.write(plan)
print("Plan updated")
